version: "2.1"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - UMASK_SET=022
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/sonarr:/config
      - /mnt/storage/series:/tv
      - /home/mateux/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:
    external: true
