version: "2.1"

services:
  openvscode-server:
    image: gitpod/openvscode-server:latest
    container_name: openvscode-server
    volumes:
      - /home/mateux:/home/workspace:cached
    ports:
      - 3000:3000
    restart: unless-stopped