version: "2.1"

services:
  webtop:
    image: lscr.io/linuxserver/webtop
    container_name: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - KEYBOARD=en-us-qwerty
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/webtop:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 6060:3000
    devices:
      - /dev/dri:/dev/dri
    shm_size: "4gb"
    restart: unless-stopped
