version: "2.1"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - torrent
