version: "2.1"

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-gke5qTV5kryXwuoTtG8e
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/sonarr/plex:/config
      - /home/mateux/storage/series:/tv:ro
      - /home/mateux/storage/movies:/movies:ro
    restart: unless-stopped