services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - WEBHOOK_TUNNEL_URL=${N8N_WEBHOOK_TUNNEL_URL}
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_METRICS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ${DOCKER_VOLUME_PATH}/n8n:/home/node/.n8n
    restart: unless-stopped
    networks:
      - services
      - tunnel
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

volumes:
  n8n_data:
    external: true

networks:
  services:
    external: true
  tunnel:
    external: true
