version: "3"

services:
  php-fpm:
    build: ./docker/php
    container_name: php-fpm
    hostname: php-fpm
    restart: always
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /Users/mateus/Sites:/var/www/html:delegated

  nginx:
    build: ./docker/nginx
    container_name: nginx
    hostname: nginx
    restart: always
    tty: true
    ports:   
      - 80:80
    volumes:
      - /Users/mateus/Sites:/var/www/html:delegated
    depends_on:
      - php-fpm
