global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['']

  - job_name: 'cadvisor'
    scrape_interval: 60s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'speedtest'
    scrape_interval: 5m
    scrape_timeout: 2m
    static_configs:
      - targets: ['speedtest-exporter:3000']
