version: "2.1"

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/homeassistant:/config
    ports:
      - 8123:8123
    restart: unless-stopped