services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=jellyfin.mateux.dev
    volumes:
      - ${DOCKER_VOLUME_PATH}/jellyfin:/config
      - ${MEDIA_PATH}/series:/data/tvshows:ro
      - ${MEDIA_PATH}/movies:/data/movies:ro
      - ${MEDIA_PATH}/music:/data/music:ro
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    networks:
      - services
      - tunnel
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 8G

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - UMASK_SET=022
    volumes:
      - ${DOCKER_VOLUME_PATH}/radarr:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/downloads:/downloads
    restart: unless-stopped
    networks:
      - services
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - UMASK_SET=022
    volumes:
      - ${DOCKER_VOLUME_PATH}/sonarr:/config
      - ${MEDIA_PATH}/series:/tv
      - ${MEDIA_PATH}/downloads:/downloads
    restart: unless-stopped
    networks:
      - torrent
      - services
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${DOCKER_VOLUME_PATH}/prowlarr:/config
    restart: unless-stopped
    networks:
      - torrent
      - services
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - TRANSMISSION_WEB_HOME=/flood-for-transmission
    volumes:
      - ${DOCKER_VOLUME_PATH}/transmission:/config
      - ${MEDIA_PATH}/downloads:/downloads
      - ${MEDIA_PATH}/downloads/watch:/watch
      - ${DOCKER_VOLUME_PATH}/flood-for-transmission:/flood-for-transmission
    restart: unless-stopped
    networks:
      - torrent
      - services
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G

networks:
  torrent:
    external: true
  services:
    external: true
  tunnel:
    external: true
