version: "2.1"

services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - UMASK_SET=022
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/radarr:/config
      - /mnt/storage/movies:/movies
      - /home/mateux/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:
    external: true