version: "3"

services:
  server:
    build: ./docker
    container_name: server
    hostname: server
    restart: always
    tty: true
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - /Users/mateus/Sites:/var/www/html:delegated # PHP projects folder