version: "2.1"

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=true
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/jacket:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:
    external: true