version: '3.4'

services:
  mc-router:
    container_name: mc-router
    image: itzg/mc-router
    environment:
      API_BINDING: ":25564"
    ports:
      - 25565:25565
      - 127.0.0.1:25564:25564
    command: --mapping=mine.gargantua.one=10.7.0.3:25565