version: "2.1"

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/mateux/projects/homer:/www/assets
    ports:
      - 8085:8080
    restart: always