services:
  mateux-dot-dev:
    image: ghcr.io/mateuxlucax/mateux-dot-dev:latest
    container_name: mateux-dot-dev
    restart: unless-stopped
    networks:
      - tunnel
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M

networks:
  tunnel:
    external: true
