version: "2.1"

services:
  openbooks:
    image: evanbuss/openbooks
    container_name: openbooks
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/storage/books:/books
    ports:
      - 7777:80
    restart: unless-stopped
