version: "2.1"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=jellyfin.gargantua.one
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/jellyfin:/config
      - /mnt/storage/series:/data/tvshows:ro
      - /mnt/storage/movies:/data/movies:ro
      - /mnt/storage/music:/data/music:ro
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
