version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7.0
    container_name: "zookeeper"
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:2.8.0
    container_name: "kafka"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
      - /srv/dev-disk-by-label-data/dockerapp/monitor-stack/server.properties:/bitnami/kafka/config/server.properties
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: "elastic"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data 
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m
      - ELASTIC_PASSWORD=monitor
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: "kibana"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=monitor
    depends_on:
      - elastic
    networks:
      - elastic-net

  memcached:
    container_name: memcached
    image: memcached:1.6.9-alpine
    ports:
        - "11211:11211"

  kafka-webview:
    container_name: kafka-webview
    image: sourcelaborg/kafka-webview:latest
    ports:
        - "6060:8080"
    volumes:
        - kafkawebview_data:/app/data
    networks:
        - kafka-net
    depends_on:
        - kafka

networks:
  elastic-net:
    external: true
  kafka-net:
    external: true

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  elastic_data:
    driver: local
  kafkawebview_data:
    driver: local
