version: "3"

services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MOTD: "Gargantua's minecraft server"
      SEED: "-1465919862"
      VIEW_DISTANCE: 16
    tty: true
    stdin_open: true
    restart: unless-stopped
    deploy:
     resources:
       limits:
         memory: 3G
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/minecraft:/data
