version: "2.1"

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/lidarr:/config
      - /mnt/storage/music:/music
      - /home/mateux/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:
    external: true