version: "2.1"

services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/
      - USER=mateux
      - PASS=8402
    volumes:
      - /srv/dev-disk-by-label-data/dockerapp/transmission:/config
      - /home/mateux/downloads:/downloads
      - /home/mateux/downloads/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:
    external: true